// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Mid.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "Mid.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace PlatPmd {

namespace {

const ::google::protobuf::EnumDescriptor* MID_descriptor_ = NULL;

}  // namespace


void protobuf_AssignDesc_Mid_2eproto() {
  protobuf_AddDesc_Mid_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "Mid.proto");
  GOOGLE_CHECK(file != NULL);
  MID_descriptor_ = file->enum_type(0);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_Mid_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
}

}  // namespace

void protobuf_ShutdownFile_Mid_2eproto() {
}

void protobuf_AddDesc_Mid_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\tMid.proto\022\007PlatPmd*\374\010\n\003MID\022\026\n\021ServerRe"
    "gisterReq\020\351\007\022\026\n\021ServerRegisterRes\020\352\007\022\022\n\r"
    "ServerListReq\020\353\007\022\022\n\rServerListRes\020\354\007\022\030\n\023"
    "ChangeRoleServerReq\020\355\007\022\030\n\023ChangeRoleServ"
    "erRes\020\356\007\022\023\n\016ServerEventReq\020\357\007\022\023\n\016ServerE"
    "ventRes\020\360\007\022\r\n\010LoginReq\020\221N\022\r\n\010LoginRes\020\222N"
    "\022\024\n\017LoginSubGameReq\020\223N\022\024\n\017LoginSubGameRe"
    "s\020\224N\022\023\n\016SystemErrorRes\020\226N\022\014\n\007QuitReq\020\227N\022"
    "\014\n\007QuitRes\020\230N\022\023\n\016QuitSubGameReq\020\231N\022\023\n\016Qu"
    "itSubGameRes\020\232N\022\r\n\010HeartReq\020\233N\022\r\n\010HeartR"
    "es\020\234N\022\022\n\rUdpConnectReq\020\235N\022\022\n\rUdpConnectR"
    "es\020\236N\022\014\n\007ChatReq\020\237N\022\014\n\007ChatRes\020\240N\022\023\n\016Pac"
    "ketItemsReq\020\241N\022\023\n\016PacketItemsRes\020\242N\022\017\n\nU"
    "seItemReq\020\243N\022\017\n\nUseItemRes\020\244N\022\020\n\013MailLis"
    "tReq\020\245N\022\020\n\013MailListRes\020\246N\022\022\n\rModifyMailR"
    "eq\020\247N\022\022\n\rModifyMailRes\020\250N\022\021\n\014GuildInfoRe"
    "q\020\251N\022\021\n\014GuildInfoRes\020\252N\022\021\n\014GuildListReq\020"
    "\253N\022\021\n\014GuildListRes\020\254N\022\022\n\rApplyGuildReq\020\255"
    "N\022\022\n\rApplyGuildRes\020\256N\022\025\n\020GuildApprovalRe"
    "q\020\257N\022\025\n\020GuildApprovalRes\020\260N\022\023\n\016CreateGui"
    "ldReq\020\261N\022\023\n\016CreateGuildRes\020\262N\022\022\n\014EnterRo"
    "omReq\020\241\234\001\022\022\n\014EnterRoomRes\020\242\234\001\022\027\n\021ApplyAt"
    "hleticsReq\020\243\234\001\022\027\n\021ApplyAthleticsRes\020\244\234\001\022"
    "\021\n\013QuitRoomReq\020\245\234\001\022\021\n\013QuitRoomRes\020\246\234\001\022\026\n"
    "\020FishEnterRoomRes\020\250\234\001\022\021\n\013RoomInfoRes\020\252\234\001"
    "\022\023\n\rRoomChangeRes\020\254\234\001\022\021\n\013UseSkillReq\020\255\234\001"
    "\022\021\n\013UseSkillRes\020\256\234\001\022\r\n\007FireReq\020\257\234\001\022\r\n\007Fi"
    "reRes\020\260\234\001\022\023\n\rFireResultReq\020\261\234\001\022\023\n\rFireRe"
    "sultRes\020\262\234\001\022\022\n\014GunLeveUpReq\020\263\234\001\022\022\n\014GunLe"
    "veUpRes\020\264\234\001", 1171);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "Mid.proto", &protobuf_RegisterTypes);
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_Mid_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_Mid_2eproto {
  StaticDescriptorInitializer_Mid_2eproto() {
    protobuf_AddDesc_Mid_2eproto();
  }
} static_descriptor_initializer_Mid_2eproto_;
const ::google::protobuf::EnumDescriptor* MID_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return MID_descriptor_;
}
bool MID_IsValid(int value) {
  switch(value) {
    case 1001:
    case 1002:
    case 1003:
    case 1004:
    case 1005:
    case 1006:
    case 1007:
    case 1008:
    case 10001:
    case 10002:
    case 10003:
    case 10004:
    case 10006:
    case 10007:
    case 10008:
    case 10009:
    case 10010:
    case 10011:
    case 10012:
    case 10013:
    case 10014:
    case 10015:
    case 10016:
    case 10017:
    case 10018:
    case 10019:
    case 10020:
    case 10021:
    case 10022:
    case 10023:
    case 10024:
    case 10025:
    case 10026:
    case 10027:
    case 10028:
    case 10029:
    case 10030:
    case 10031:
    case 10032:
    case 10033:
    case 10034:
    case 20001:
    case 20002:
    case 20003:
    case 20004:
    case 20005:
    case 20006:
    case 20008:
    case 20010:
    case 20012:
    case 20013:
    case 20014:
    case 20015:
    case 20016:
    case 20017:
    case 20018:
    case 20019:
    case 20020:
      return true;
    default:
      return false;
  }
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace PlatPmd

// @@protoc_insertion_point(global_scope)
